baseURL = "https://icoc.com.co"
languageCode = "es-co"
title = "Odoo de Calidad para Colombia"
theme = "LeaveIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[params]
    since = 2019
    author = "Una inicitativa de XOE Solutions y Nubark"                           # Author's name
    avatar = "/images/logo.png"           # Author's avatar
    avatar_dark = "/images/logo_dark.png"           # Author's avatar
    subtitle = "Descubre nuestros valores y compromisos ..."         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "other" # post or other

    google_verification = ""
   
    description = "" # site description
    keywords = "" # site keywords

    beian = ""
    baiduAnalytics = ""

    license= 'Licence: <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a> - ¡respétala!'

# [params.social]
#     GitHub = "xxoo"
#     Twitter = "xxoo"
#     Email   = "xxoo"
#     Instagram = "xxoo"
#     Wechat = "/images/me/wechat.png"  # Wechat QRcode image
#     Facebook = "xxoo"
#     Telegram = "xxoo"
#     Dribbble = "xxoo"
#     Medium = "xxoo"

